export const mockProjectMeta = {
  projectName: 'depSCAN Core',
  author: 'Member 6',
  timestamp: '2026-06-03T14:20:00Z',
  complianceScore: 88,
  compliancePercentage: 88,
  totalComponents: 10,
  totalDependencies: 12,
  totalVulnerabilities: 9,
};

export const mockComponents = [
  {
    name: 'django',
    version: '4.2.1',
    supplier: { name: 'Django Software Foundation' },
    purl: 'pkg:pypi/django@4.2.1',
    licenses: [{ license: { id: 'BSD-3-Clause' } }],
    author: 'Django Team',
    status: 'pass',
    severity: 'high',
  },
  {
    name: 'sqlparse',
    version: '0.4.4',
    supplier: { name: 'Python Packaging Authority' },
    purl: 'pkg:pypi/sqlparse@0.4.4',
    licenses: [{ license: { id: 'BSD-3-Clause' } }],
    author: 'SQLParse Contributors',
    status: 'pass',
    severity: 'medium',
  },
  {
    name: 'asgiref',
    version: '3.8.0',
    supplier: { name: 'Django Software Foundation' },
    purl: 'pkg:pypi/asgiref@3.8.0',
    licenses: [{ license: { id: 'BSD-3-Clause' } }],
    author: 'ASGI Contributors',
    status: 'pass',
    severity: 'low',
  },
  {
    name: 'requests',
    version: '2.31.0',
    supplier: { name: 'Python Packaging Authority' },
    purl: 'pkg:pypi/requests@2.31.0',
    licenses: [{ license: { id: 'Apache-2.0' } }],
    author: 'Kenneth Reitz',
    status: 'pass',
    severity: 'medium',
  },
  {
    name: 'urllib3',
    version: '2.0.4',
    supplier: { name: 'Python Packaging Authority' },
    purl: 'pkg:pypi/urllib3@2.0.4',
    licenses: [{ license: { id: 'MIT' } }],
    author: 'urllib3 Contributors',
    status: 'pass',
    severity: 'low',
  },
  {
    name: 'certifi',
    version: '2025.11.3',
    supplier: { name: 'Python Packaging Authority' },
    purl: 'pkg:pypi/certifi@2025.11.3',
    licenses: [{ license: { id: 'MPL-2.0' } }],
    author: 'Mozilla',
    status: 'pass',
    severity: 'low',
  },
  {
    name: 'numpy',
    version: '2.1.0',
    supplier: { name: 'NumPy Developers' },
    purl: 'pkg:pypi/numpy@2.1.0',
    licenses: [{ license: { id: 'BSD-3-Clause' } }],
    author: 'NumPy Community',
    status: 'pass',
    severity: 'safe',
  },
  {
    name: 'react',
    version: '19.2.6',
    supplier: { name: 'Meta Platforms, Inc.' },
    purl: 'pkg:npm/react@19.2.6',
    licenses: [{ license: { id: 'MIT' } }],
    author: 'Facebook Open Source',
    status: 'pass',
    severity: 'medium',
  },
  {
    name: 'axios',
    version: '1.7.0',
    supplier: { name: 'Axios Contributors' },
    purl: 'pkg:npm/axios@1.7.0',
    licenses: [{ license: { id: 'MIT' } }],
    author: 'Axios Team',
    status: 'pass',
    severity: 'high',
  },
  {
    name: 'express',
    version: '4.18.4',
    supplier: { name: 'OpenJS Foundation' },
    purl: 'pkg:npm/express@4.18.4',
    licenses: [{ license: { id: 'MIT' } }],
    author: 'Express Contributors',
    status: 'pass',
    severity: 'medium',
  },
];

export const dependencyTree = [
  {
    id: 'depSCAN',
    name: 'depSCAN',
    version: '1.0.0',
    supplier: { name: 'depSCAN Security' },
    purl: 'pkg:github/depSCAN/depSCAN@1.0.0',
    licenses: [{ license: { id: 'MIT' } }],
    severity: 'safe',
    children: [
      {
        id: 'django',
        name: 'django',
        version: '4.2.1',
        supplier: { name: 'Django Software Foundation' },
        purl: 'pkg:pypi/django@4.2.1',
        severity: 'high',
        children: [
          {
            id: 'sqlparse',
            name: 'sqlparse',
            version: '0.4.4',
            supplier: { name: 'Python Packaging Authority' },
            purl: 'pkg:pypi/sqlparse@0.4.4',
            severity: 'medium',
            children: [],
          },
          {
            id: 'asgiref',
            name: 'asgiref',
            version: '3.8.0',
            supplier: { name: 'Django Software Foundation' },
            purl: 'pkg:pypi/asgiref@3.8.0',
            severity: 'low',
            children: [],
          },
          {
            id: 'pytz',
            name: 'pytz',
            version: '2025.7',
            supplier: { name: 'Python Packaging Authority' },
            purl: 'pkg:pypi/pytz@2025.7',
            severity: 'low',
            children: [],
          },
        ],
      },
      {
        id: 'requests',
        name: 'requests',
        version: '2.31.0',
        supplier: { name: 'Python Packaging Authority' },
        purl: 'pkg:pypi/requests@2.31.0',
        severity: 'medium',
        children: [
          {
            id: 'urllib3',
            name: 'urllib3',
            version: '2.0.4',
            supplier: { name: 'Python Packaging Authority' },
            purl: 'pkg:pypi/urllib3@2.0.4',
            severity: 'low',
            children: [],
          },
          {
            id: 'certifi',
            name: 'certifi',
            version: '2025.11.3',
            supplier: { name: 'Python Packaging Authority' },
            purl: 'pkg:pypi/certifi@2025.11.3',
            severity: 'low',
            children: [],
          },
          {
            id: 'charset-normalizer',
            name: 'charset-normalizer',
            version: '3.3.0',
            supplier: { name: 'Python Packaging Authority' },
            purl: 'pkg:pypi/charset-normalizer@3.3.0',
            severity: 'low',
            children: [],
          },
        ],
      },
      {
        id: 'numpy',
        name: 'numpy',
        version: '2.1.0',
        supplier: { name: 'NumPy Developers' },
        purl: 'pkg:pypi/numpy@2.1.0',
        severity: 'safe',
        children: [],
      },
      {
        id: 'react',
        name: 'react',
        version: '19.2.6',
        supplier: { name: 'Meta Platforms, Inc.' },
        purl: 'pkg:npm/react@19.2.6',
        severity: 'medium',
        children: [
          {
            id: 'axios',
            name: 'axios',
            version: '1.7.0',
            supplier: { name: 'Axios Contributors' },
            purl: 'pkg:npm/axios@1.7.0',
            severity: 'high',
            children: [],
          },
          {
            id: 'express',
            name: 'express',
            version: '4.18.4',
            supplier: { name: 'OpenJS Foundation' },
            purl: 'pkg:npm/express@4.18.4',
            severity: 'medium',
            children: [],
          },
        ],
      },
    ],
  },
];

export const mockDependencies = [
  { parent: 'depSCAN', child: 'django' },
  { parent: 'depSCAN', child: 'requests' },
  { parent: 'depSCAN', child: 'numpy' },
  { parent: 'depSCAN', child: 'react' },
  { parent: 'django', child: 'sqlparse' },
  { parent: 'django', child: 'asgiref' },
  { parent: 'django', child: 'pytz' },
  { parent: 'requests', child: 'urllib3' },
  { parent: 'requests', child: 'certifi' },
  { parent: 'requests', child: 'charset-normalizer' },
  { parent: 'react', child: 'axios' },
  { parent: 'react', child: 'express' },
];

export const mockVulnerabilities = [
  {
    package: 'django',
    version: '4.2.1',
    cve: 'CVE-2026-1234',
    severity: 'High',
    cvss: 8.2,
    fixedVersion: '4.2.2',
    description: 'Template injection vulnerability in admin interface.',
  },
  {
    package: 'requests',
    version: '2.31.0',
    cve: 'CVE-2026-2345',
    severity: 'Medium',
    cvss: 6.1,
    fixedVersion: '2.31.1',
    description: 'Improper certificate validation under certain proxy configurations.',
  },
  {
    package: 'axios',
    version: '1.7.0',
    cve: 'CVE-2026-3456',
    severity: 'High',
    cvss: 8.7,
    fixedVersion: '1.7.1',
    description: 'Prototype pollution in URL parsing module.',
  },
  {
    package: 'react',
    version: '19.2.6',
    cve: 'CVE-2026-4567',
    severity: 'Medium',
    cvss: 5.9,
    fixedVersion: '19.2.7',
    description: 'Cross-site scripting risk in development warnings.',
  },
  {
    package: 'sqlparse',
    version: '0.4.4',
    cve: 'CVE-2026-5678',
    severity: 'Low',
    cvss: 3.1,
    fixedVersion: '0.4.5',
    description: 'SQL parsing edge case could reveal parser state.',
  },
  {
    package: 'certifi',
    version: '2025.11.3',
    cve: 'CVE-2026-6789',
    severity: 'Low',
    cvss: 2.8,
    fixedVersion: '2026.1.0',
    description: 'Certificate bundle update needed for new root CA.',
  },
  {
    package: 'urllib3',
    version: '2.0.4',
    cve: 'CVE-2026-7890',
    severity: 'Medium',
    cvss: 6.5,
    fixedVersion: '2.0.5',
    description: 'HTTP header injection vulnerability in redirect handling.',
  },
  {
    package: 'express',
    version: '4.18.4',
    cve: 'CVE-2026-8901',
    severity: 'Medium',
    cvss: 5.4,
    fixedVersion: '4.18.5',
    description: 'Unsafe request parameter parsing in legacy middleware.',
  },
  {
    package: 'asgiref',
    version: '3.8.0',
    cve: 'CVE-2026-9012',
    severity: 'Low',
    cvss: 3.7,
    fixedVersion: '3.8.1',
    description: 'Async context propagation could leak user data in certain cases.',
  },
];

export const mockReportSummary = {
  projectName: 'depSCAN Core',
  scanDate: '2026-06-03',
  complianceScore: 88,
  compliancePercentage: 88,
  components: mockComponents.length,
  dependencies: mockDependencies.length,
  vulnerabilities: mockVulnerabilities.length,
  critical: 0,
  high: 2,
  medium: 5,
  low: 2,
  author: 'Member 6',
  timestamp: '2026-06-03T14:20:00Z',
  summary: 'The SBOM scan identified the core dependency graph and flagged package-level vulnerability findings. Compliance is strong overall, but a focused patch cycle is recommended for high-severity dependencies.',
};
